### ISSUE TITLE
Support build on Linux

### ISSUE THREAD

**Issue by stardiviner** [mgmart/EverOrg#1]
I want to use this application, can you add a section for installation? (I'm an Linux user)

**Comment by mgmart** [comment]
Unfortunately this does not work out of the box as Swift for Linux depends on it's Package Manager. I'd be happy if there is someone who could take the necessary steps to build the project on Linux. 

It might be a simple tasks like creating a proper `Package.swift` and building it. But maybe there are more hurdles lurking behind it. One constriction could be the `Bridging-Header.h` which imports some constants for `MD5`. If that's the case we could hard code those for the time being.

**Comment by stardiviner** [comment]
Don't know how to install Swift package under Linux. Can't help on this work.

**Comment by mgmart** [comment]
It seemed that it was not as straightforward as I thought to build a Xcode project on Linux. I rewrote EverOrg in Go. Please find a binary versions in the releases section.

**Comment by stardiviner** [comment]
Thanks, I will try the new Go version out. Really quick development.
