### ISSUE TITLE
New lines are omitted if no `<br/>` tag is present in the `.enex` file

### ISSUE THREAD

**Issue by idanov** [mgmart/EverOrg#10]
Sometimes Evernote doesn't add `<br/>` tags on a new line, but just creates the new line as a separate `<div>` element. `EverOrg` ignores all `<div>` tags https://github.com/mgmart/EverOrg/blob/57aabb6a5a8c383d7b95e3b06665fcdca0c9da27/everorg.go#L143-L145
which causes the resulting org to concatenate different lines, which breaks badly the layout quite often. Could the behaviour be modified such that it adds a new line after each `</div>`, since extra new lines are easy to get rid of, but missing ones can be destroying the note layout significantly?

**Comment by mgmart** [comment]
Should be easy to implement. Will see if I can add this quickly. Haven't worked on this for years. Probably I would have to update the whole thing to the newest go version.

**Comment by mgmart** [comment]
@idanov could you please test the new release? Could you please also mention the platform(s) on which you habe tested?

**Comment by idanov** [comment]
I've tested it on macOS, Intel chip. It works great now - there's no side effects, except an extra new line here or there (mainly in lists), but nothing horribly bad. Thanks a lot for the amazingly fast response @mgmart!

Here's a bit of my test:

My Evernote note:
![image](https://user-images.githubusercontent.com/3482916/211286650-eab3f791-b727-48f2-9cee-369ad2cad288.png)



My `example.enex`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export3.dtd">
<en-export export-date="20230109T095448Z" application="Evernote" version="Evernote Mac 7.14 (458244)">
<note><title>Important places</title><content><![CDATA[<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div>Home</div><div>Work</div><div>GP</div><div>Nursery</div><div>Barber</div><div>Dentist</div><div>Hospital</div><div>Airport</div></en-note>]]></content><created>20200912T204018Z</created><updated>20230109T095427Z</updated><note-attributes><author>Ivan Danov</author><reminder-order>0</reminder-order></note-attributes></note>
</en-export>
```

After running `everorg --input="example.enex" --merge=True`:
```

* Important places
:PROPERTIES:
:AUTHOR: Ivan Danov
:EVNT_CREATED: 20200912T204018Z
:EVNT_UPDATED: 20230109T095427Z
:END:
HomeWorkGPNurseryBarberDentistHospitalAirport
```

After running `everorg --input="example.enex" --merge=True --regardDiv=True`:
```

* Important places
:PROPERTIES:
:AUTHOR: Ivan Danov
:EVNT_CREATED: 20200912T204018Z
:EVNT_UPDATED: 20230109T095427Z
:END:
Home
Work
GP
Nursery
Barber
Dentist
Hospital
Airport
```
