### ISSUE TITLE
Only one attachment is extracted

### ISSUE THREAD

**Issue by carlco** [mgmart/EverOrg#2]
Running everOrg (osx 64bits) from the binary version 0.1 on Evernote entries containing multiple attachments only extracts one file per entry.

I'll take a look at the code and try to submit a pull request (it's going to be my first time programming in Go ;-). Otherwise, thanks for publishing this work, I was about to write the same thing myself ... you made my day.

**Comment by mgmart** [comment]
Would appreciate that. Those are also for me the first steps with go. :smile:

**Comment by mgmart** [comment]
@carlco, I'd realised that only a small tweak was needed. Please reopen if issue still persists for you.

**Comment by carlco** [comment]
@mgmart works like a charm, thanks a lot!
